// Generated using Sourcery 1.9.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// 💙💙 Autogenerated for saving Beegees time ⏰
// swiftlint:disable all

@testable import HPSample
import Foundation

extension CharacterViewModel {
    static func fixture(
        character: Character = .fixture()
    ) -> CharacterViewModel {
        return .init(
            character: character
        )
    }
}
