// Generated using Sourcery 1.9.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// 💙💙 Autogenerated for saving Beegees time ⏰
// swiftlint:disable all

@testable import HPSample
import Foundation

extension Character {
    static func fixture(
        name: String = "Lorem ipsum",
        species: String = "Lorem ipsum",
        gender: String = "Lorem ipsum",
        house: String = "Lorem ipsum",
        dateOfBirth: String = "Lorem ipsum",
        yearOfBirth: Int? = 1980,
        wizard: Bool = true,
        ancestry: String = "Lorem ipsum",
        eyeColour: String = "Lorem ipsum",
        hairColour: String = "Lorem ipsum",
        patronus: String = "Lorem ipsum",
        hogwartsStudent: Bool = true,
        hogwartsStaff: Bool = true,
        actor: String = "Lorem ipsum",
        alive: Bool = true,
        image: String = "Lorem ipsum"
    ) -> Character {
        return .init(
            name: name,
            species: species,
            gender: gender,
            house: house,
            dateOfBirth: dateOfBirth,
            yearOfBirth: yearOfBirth,
            wizard: wizard,
            ancestry: ancestry,
            eyeColour: eyeColour,
            hairColour: hairColour,
            patronus: patronus,
            hogwartsStudent: hogwartsStudent,
            hogwartsStaff: hogwartsStaff,
            actor: actor,
            alive: alive,
            image: image
        )
    }
}
